### ISSUE TITLE
Chinese passport validation fails

### ISSUE THREAD

**Issue by jvanderbiest** [cheminfo/mrz#34]
We are using this awesome library to validate a few legit Chinese e-passports (TD3). I used the library's tests suite to verify many other countries but these Chinese ones all fail on the  `personal number check digit´. Also notice on this example the document type is PO not just P.

I'm afraid I can't share any example as it's PII, so is there any way I can provide you more infomation without disclosing the individual?

![image](https://user-images.githubusercontent.com/3985995/214333066-bab987b2-3f10-4506-ba1f-72bd6b83de48.png)

**Comment by lpatiny** [comment]
I added 2 examples of CHN passport that I found on the web and both are passing the tests:

https://github.com/cheminfo/mrz/commit/7b6bd38e2421fbb7947e520232e9aedbc2e8266b

If you can find a specific bug or provide a specific test case that fails you may create a PR but otherwise I don't see what we can do.
