### ISSUE TITLE
Pin code in details but not in fields

### ISSUE THREAD

**Issue by stropitek** [cheminfo/mrz#42]
I noticed that the PIN code appears in the details but does not appear in the fields. Any ideas why?

@josoriom

![CleanShot 2023-09-25 at 11 50 24](https://github.com/zakodium/components/assets/4118690/01a7a5d0-24c2-46d1-9182-de034d5e8dd6)

https://github.com/zakodium/components/pull/1227

**Comment by josoriom** [comment]
![screenshot-001](https://github.com/cheminfo/mrz/assets/31483796/c0c58ff0-3e36-4f09-a551-a34c0f51c126)
The code itself has some issues. In the component, the parse function has autocorrect enabled, but in the Storybook, it doesn't. Due to these issues in the code, it would lead to null values because they are not valid.

**Comment by stropitek** [comment]
It's definitely worth mentioning that some characters have been auto-corrected. Those characters should probably be highlighted in some way.

But to start, could you put a warning icon next to the corrected label indicating that the read value has be auto-corrected (with text in a tooltip).

![CleanShot 2023-09-26 at 12 22 44](https://github.com/cheminfo/mrz/assets/4118690/baeca0bb-a1a5-4b01-b505-991f7ea26488)

I'm transfering the issue to components.

**Comment by stropitek** [comment]
Cannot transfer, so closing and opening another issue in the right repo
